### ISSUE TITLE
Default values don't match documentation

### ISSUE THREAD

**Issue by gsingh93** [Arth-ur/bitfield#1]
Looking at the [options section](https://github.com/Arth-ur/bitfield#options) of the README, I see that the default value for `--hspace` is 640 and the default value for `--lanes` is 2.

But if I look at [the code](https://github.com/Arth-ur/bitfield/blob/master/bit_field/__main__.py#L13-L14), I see different default values:
```
parser.add_argument('--hspace', help='horizontal space', default=800, type=int)
parser.add_argument('--lanes', help='rectangle lanes', default=1, type=int)
```

I noticed this after running the example in the README and getting an image that looked different than expected.

**Comment by Arth-ur** [comment]
Fixed, thanks !
