### ISSUE TITLE
`--bigendian` is included in the README but not implemented

### ISSUE THREAD

**Issue by gsingh93** [Arth-ur/bitfield#2]
It looks like the `--bigendian` flag is not implemented based on a quick glance at the code and the fact that using it doesn't change the output image. It should be removed as an argument and from the README until it's implemented to avoid any confusion.

**Comment by Arth-ur** [comment]
Yes, you're right, it does not do anything like in the [original work](https://github.com/wavedrom/bitfield). I have removed the flag and plan to add the implementation for flags `vflip` and `hflip`.
